FROM xdmod-openstack

RUN cd /app \
    && wget https://r.mariadb.com/downloads/mariadb_repo_setup
RUN apt-get install mariadb-server mariadb-client -y
RUN pip install pyTest
RUN mkdir /app/test

COPY process_hierarchy.py /app/process_hierarchy.py
COPY moc_db_helper_functions.py /app/moc_db_helper_functions.py
COPY get_users_from_keycloak.py /app/get_users_from_keycloak.py
COPY test/*.py /app/test

CMD ["/usr/bin/sleep","10000"]

WORKDIR /
