apiVersion: batch/v1
kind: CronJob
metadata:
  name: cj-xdmod-openstack
spec:
  schedule: "0/20 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: cj-init-xdmod-openstack
              image: image-registry.openshift-image-registry.svc:5000/xdmod/xdmod-openstack:latest
              env:
                - name: OPENSTACK_INSTANCE
                  value: "nerc-openstack"
          containers:
            - name: xdmod-openstack-backup
              image: image-registry.openshift-image-registry.svc:5000/xdmod/xdmod-openstack:latest
            - name: cj-xdmod-openstack
              image: image-registry.openshift-image-registry.svc:5000/xdmod/moc-xdmod:latest
              imagePullPolicy: Always
              command:
                - xdmod-shredder
              args:
                [
                  "--debug",
                  "-f",
                  "openstack",
                  "-d",
                  "/data",
                  "-r",
                  "nerc_openstack",
                ]
